- name: ansible datatypes
  hosts: local
  connection: local
  vars: 
    DURATION: 120 # number, int
    COURSE: DevSecOps # string
    IS_LIVE: true # Boolean
    TOOLS: # List []
    - Linux
    - Shell
    - Ansible
    CONCEPTS: # map or dictonary or object, referred like {}
      CI: Jenkins
      SCRIPTING: "Shell. Ansible, Terraform"
  tasks: 
  - name: print course information
    ansible.builtin.debug:
    msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, is live {{ IS_LIVE }}, Tools are: {{ TOOLS}}, Concepts are: {{ CONCEPTS }}"