- name: playbook control using ansible facts
  hosts: frontend
  become: yes

  tasks:

  - name: install nginx if Redhat
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Enable and Start Nginx
    ansible.builtin.service:
      state: started
      enabled: yes

  - name: install nginx if Debian
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"