- name: install and packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name : 'nginx', state: 'present' }
    - { name : 'mysql', state: 'absent' }
    - { name : 'zip', state: 'absent' }


  #     name: "{{ item }}"
  #     state: present
  #   loop:
  #   - nginx
  #   - zip

  # - name: remove package
  #   ansible.builtin.package:
  #     name: "{{ item }}"
  #     state: absent
  #   loop:
  #   - mysql
  #   - zip
    

