- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"

  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons }}"
  
  - name: print names by splitting
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: DevSecOps
        duration: 120HR
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

      