- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"

  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | default('Ramesh') }}"

  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons }}"
  
  - name: print names by splitting
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split (',') }}"

  - name: convert map into list
    vars:
      course:
        name: DevSecOps
        duration: 120HR
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      TOOLS: 
      - {'key': 'name', 'value': 'Ansible'}
      - {'key': 'name1', 'value': 'Terraform'}
      - {'key': 'name2', 'value': 'Jenkins'}
    ansible.builtin.debug:
      msg: "Tools used are: {{ TOOLS | items2dict }}"